-intstyle "ise" -incremental -o "C:/Users/jeanw/Desktop/VHDL/vhdl_calculator/mult_block_tb_isim_beh.exe" -prj "C:/Users/jeanw/Desktop/VHDL/vhdl_calculator/mult_block_tb_beh.prj" "work.mult_block_tb" 
